### ISSUE TITLE
Dependabot builds fail

### ISSUE THREAD

**Issue by ivanoblomov** [FoveaCentral/google_maps_geocoder#116]
# Description

Builds for Dependabot pull requests fail due to missing Maps API keys:
```ruby
  20) GoogleMapsGeocoder#new with "White House" Geocoder API 
      Failure/Error: raise GeocodingError, @json if !@json || @json.empty? || status != 'OK'

      GoogleMapsGeocoder::GeocodingError:
        {"error_message"=>"You must use an API key to authenticate each request to Google Maps Platform APIs. For additional information, please refer to http://g.co/dev/maps-no-account", "results"=>[], "status"=>"REQUEST_DENIED"}
      # ./lib/google_maps_geocoder/google_maps_geocoder.rb:77:in `initialize'
      # ./spec/lib/google_maps_geocoder_spec.rb:11:in `new'
      # ./spec/lib/google_maps_geocoder_spec.rb:11:in `block (4 levels) in <top (required)>'
      # ./spec/lib/google_maps_geocoder_spec.rb:53:in `block (5 levels) in <top (required)>'

Finished in 0.70987 seconds (files took 0.22111 seconds to load)
21 examples, 20 failures
```

# Steps to Reproduce

1. Rerun [failing](https://github.com/FoveaCentral/google_maps_geocoder/actions/runs/8462057294/job/23248994391) [builds](https://github.com/FoveaCentral/google_maps_geocoder/actions/runs/8610090004/job/23595255295) for #114, #115.

**Comment by ivanoblomov** [comment]
Perhaps adding Dependabot to the org fixes this?
